version: '3'
services:
  web1:
    build: .
    ports:
      - "8083:8081" # expose the port to other containers, but it's not exposed to the host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/prueba
      - SERVER_PORT=8081
    links:
      - db
    restart: unless-stopped # Restart the container. Necessary to avoid problems if the app starts before the db is ready
  web2:
    build: .
    ports:
      - "8084:8082" # expose the port to other containers, but it's not exposed to the host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/prueba
      - SERVER_PORT=8082
    links:
      - db
    restart: unless-stopped # Restart the container. Necessary to avoid problems if the app starts before the db is ready
  si1:
    build: ../SistemaInterno
    expose:
      - "8083" # expose the port to other containers, but it's not exposed to the host
    environment:
      - SERVER_PORT=8083
  si2:
    build: ../SistemaInterno
    expose:
      - "8084" # expose the port to other containers, but it's not exposed to the host
    environment:
      - SERVER_PORT=8084
  lbsi:
    image: haproxy:1.9.6
    ports:
      - "443:443" # Only service that is exposed to the host is the lb
      - "80:80"
    expose:
      - "8888"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    restart: unless-stopped
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=prueba
      - MYSQL_USER=libro
      - MYSQL_PASSWORD=libro


